import Color from './color';
import {StyleSheet, Dimensions} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {fonts} from './fonts';
import {WP, HP} from '../utilies/responsives/responsive';

const height = Dimensions.get('screen').height;
const width = Dimensions.get('screen').width;

const IOSShadow = {
  shadowColor: '#000',
  shadowOffset: {
    width: 0,
    height: 2,
  },
  shadowOpacity: 0.25,
  shadowRadius: 3.84,
};

const Theme = StyleSheet.create({
  FormInputTitle: {
    // fontFamily: fonts.regular,
    color: 'grey',
    marginBottom: 5,
    fontSize: 14,
  },
  ProfileImgLoader: {
    position: 'absolute',
    zIndex: 1,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
    flex: 1,
    height: '100%',
    width: '100%',
    borderRadius: 72,
  },
  CameraIcon: {
    position: 'absolute',
    zIndex: 1,
    bottom: 0,
    right: 0,
    backgroundColor: 'grey',
    borderRadius: 20,
    padding: 4,
  },
  ProfileImg: {
    flex: 1,
    borderRadius: 72,
    width: '100%',
    height: '100%',
  },
  ProfileImgContainer: {
    elevation: 3,
    width: 72,
    height: 72,
    borderWidth: 1,
    borderRadius: 72,
    borderColor: 'lightgrey',
    ...IOSShadow,
  },
  OrderCardStatus: {
    fontFamily: fonts.light,
    fontSize: 10,
    alignSelf: 'center',
    marginTop: 5,
  },
  AlertBoxHeading: {
    fontFamily: fonts.bold,
    textAlign: 'center',
    fontSize: 16,
    color: 'black',
    marginTop: 10,
  },
  AlertBoxContainer: {
    backgroundColor: 'white',
    elevation: 10,
    height: '22%',
    width: '85%',
    alignSelf: 'center',
    marginHorizontal: '5%',
    paddingHorizontal: '5%',
    borderColor: Color.ThemeColor,
    borderWidth: 1,
    borderRadius: 5,
  },
  CartDeleteBtn: {
    fontFamily: fonts.medium,
    color: 'grey',
    marginRight: 20,
    borderRadius: 10,
    borderWidth: 0.5,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderColor: Color.ThemeColor,
    backgroundColor: 'white',
    elevation: 4,
  },
  FormInputListDesign: {
    elevation: 5,
    backgroundColor: '#fff',
    shadowOffset: {width: 1, height: 1},
    shadowColor: 'black',
    shadowOpacity: 0.3,
    shadowRadius: 5,
    marginTop: 5,
    marginHorizontal: 4,
    elevation: 3,
    borderRadius: 5,
    paddingHorizontal: 8,
    position: 'absolute',
    width: '95%',
    alignSelf: 'center',
    top: '80%',
    zIndex: 1,
  },
  DashedBorder: {
    borderBottomColor: Color.borderColors,
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    marginTop: 12,
  },
  CarousalImage: {flex: 1, width: null, height: null, borderRadius: 5},
  CarousalContaioner: {
    marginHorizontal: '4%',
    borderRadius: 5,
    marginTop: '3%',
  },
  CarousalDotContainer: {
    flexDirection: 'row',
    marginTop: 10,
    justifyContent: 'center',
  },
  CarousalInActiveDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginHorizontal: 5,
    backgroundColor: Color.borderColors,
  },
  CarousalActiveDot: {
    width: 20,
    height: 10,
    borderRadius: 5,
    marginHorizontal: 5,
    backgroundColor: Color.ThemeColor,
  },
  ANameCrudContainer: {
    flexDirection: 'row',
    marginBottom: '2%',
    justifyContent: 'space-between',
    backgroundColor: Color.offWhite,
    marginTop: 10,
    padding: 10,
    borderRadius: 4,
  },
  AUserCardContainer: {
    flex: 1,
    marginBottom: '2%',
    backgroundColor: Color.offWhite,
    marginTop: 10,
    padding: 10,
    borderRadius: 4,
  },
  BadgeText: {
    marginRight: 5,
    color: 'white',
    fontFamily: 'Metropolis-Medium',
    fontSize: 12,
  },
  BadgeContainer: {
    flexDirection: 'row',
    backgroundColor: Color.ThemeColor,
    elevation: 5,
    borderRadius: 10,
    paddingHorizontal: 6,
    alignItems: 'center',
    marginHorizontal: wp('1%'),
    marginBottom: 8,
    marginTop: 2,
    paddingVertical: 2.5,
  },
  AddViewListMargin: {
    marginHorizontal: '5%',
    marginTop: '2%',
  },
  ScrollViewMargins: {
    marginTop: '4%',
    marginBottom: '2%',
  },
  FormInputTitle: {
    fontFamily: fonts.regular,
    color: 'grey',
    marginBottom: 5,
    fontSize: 14,
  },
  CreateViewHeading: {
    fontFamily: fonts.bold,
    fontSize: 14,
    marginLeft: '4%',
    marginTop: '4%',
    marginBottom: '-2%',
    color: 'black',
  },
  TabViewCreateInsideContainer: {
    flex: 1,
    backgroundColor: 'white',
    margin: '5%',
    elevation: 10,
    borderRadius: 5,
  },
  TabViewCreateContainer: {
    backgroundColor: 'white',
    width: '90%',
    alignSelf: 'center',
    borderRadius: 5,
    marginTop: '2%',
    elevation: 10,
  },
  TabViewCreateIndicator: {
    backgroundColor: Color.ThemeColor,
    width: '45%',
    marginHorizontal: 10,
  },
  OrderCardMain: {
    marginHorizontal: '4%',
    marginTop: '1%',
    backgroundColor: 'white',
    elevation: 4,
    marginBottom: wp('2%'),
    borderRadius: 5,
    paddingVertical: '2%',
    paddingLeft: '2%',
  },
  OrderCardRightContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  OrderCardSub: {color: 'grey', fontSize: 12, fontFamily: fonts.medium},
  OrderCardTitle: {color: Color.headingColor, fontFamily: fonts.bold},
  Number: {
    fontFamily: fonts.bold,
    fontSize: 12,
    color: Color.ThemeColor,
    textAlign: 'right',
  },
  DTCSeprator: {
    height: 0.5,
    width: '80%',
    backgroundColor: Color.ThemeColorBlueDark,
    marginVertical: 5,
  },
  container: {
    flex: 1,
    backgroundColor: Color.white,
  },
  containerOffWhite: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  Authheading: {
    color: Color.headingColor,
    fontSize: 17,
    textAlign: 'center',
    letterSpacing: 0.5,
    fontWeight: '700',
    marginTop: '6%',
    fontFamily: fonts.regular,
  },
  subHeading: {
    color: Color.neutralGray,
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0.5,
    textAlign: 'center',
    marginTop: '2%',
  },
  InputView: {
    backgroundColor: '#fff',
    borderColor: Color.borderColors,
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: '3%',
    fontWeight: 'bold',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 2,
  },
  TextInputStyle: {
    color: '#9098B1',
    fontFamily: 'Metropolis-Medium',
    flex: 1,
    fontSize: 12,
    textAlignVertical: 'center',
    height: 40,
  },
  TextInputContainer: {marginVertical: '2.5%', marginHorizontal: '4%'},
  btnStyle: {
    marginTop: HP(3),
    backgroundColor: Color.ThemeColor,
    borderRadius: 5,
    // marginBottom: WP(10),
    borderColor: Color.ThemeColor,
    borderWidth: 0.5,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    marginHorizontal: '4%',
  },
  btnTextstyle: {
    color: '#FFFFFF',
    paddingVertical: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  BorderOrView: {
    borderBottomColor: Color.borderColors,
    borderWidth: 0.4,
    marginHorizontal: '3.5%',
    marginTop: '10%',
    height: 0,
  },
  BorderOrText: {
    height: 20,
    marginTop: -11,
    textAlign: 'center',
    color: Color.neutralGray,
    fontSize: 14,
    fontWeight: '700',
    backgroundColor: 'white',
    width: '20%',
    alignSelf: 'center',
  },
  FormInputLeftIcon: {width: 23, marginRight: 5},
  socialBtnStyle: {
    borderColor: Color.borderColors,
    borderWidth: 1,
    paddingVertical: '3%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    backgroundColor: 'white',
    elevation: 2,
    borderRadius: 5,
    flexDirection: 'row',
    marginTop: HP(2),
    marginHorizontal: '4%',
  },
  SocialBtnTextstyle: {
    flex: 1,
    color: Color.neutralGray,
    fontSize: 14,
    fontFamily: fonts.bold,
    textAlign: 'center',
    fontWeight: '700',
  },
  SearchItemList: {
    color: 'black',
    paddingHorizontal: '5%',
    fontSize: 13,
    fontFamily: fonts.medium,
    textAlignVertical: 'center',
  },
  rowbetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  MenuHeaderTxt1: {
    color: Color.headingColor,
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  MenuHeaderTxt2: {
    color: Color.ThemeColor,
    fontSize: 14,
    fontFamily: 'Metropolis-Medium',
    fontWeight: '700',
  },
  iconTextIconContainer: {
    borderColor: Color.borderColors,
    borderWidth: 1.5,
    borderRadius: 1000,
    height: wp('10%'),
    width: wp('10%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconTextFontContainer: {
    textAlign: 'center',
    alignSelf: 'center',
    color: Color.neutralGray,
    fontSize: wp('2.4%'),
    fontWeight: '400',
    fontFamily: fonts.medium,
    marginTop: 5,
  },
  ProductView1Title: {
    fontFamily: 'Metropolis-Medium',
    marginTop: 10,
    color: Color.headingColor,
    fontSize: 12,
    fontWeight: '700',
    height: 30,
  },
  ProductView1OrignalPrice: {
    fontFamily: 'Metropolis-Medium',
    color: Color.neutralGray,
    fontSize: 10,
    fontWeight: '400',
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
  },
  ProductView1Percent: {
    color: '#FB7181',
    fontSize: 10,
    fontWeight: '700',
    fontFamily: 'Metropolis-Medium',
  },
  ProductView1Image: {
    height: '100%',
    width: '100%',
    borderRadius: 5,
    alignSelf: 'center',
  },
  ProductView1Container: {
    flex: 1,
    borderRadius: 5,
    borderColor: Color.borderColors,
    borderWidth: 1,
    elevation: 2,
    backgroundColor: 'white',
    // padding: '4%',
    margin: '2%',
  },
  ProductView1Like: {
    position: 'absolute',
    right: 10,
    top: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ProductView1LikeBtn: {
    elevation: 5,
    ...IOSShadow,
  },
  TabsViewTitle: {
    fontFamily: 'Metropolis-Medium',
    fontSize: 16,
    marginTop: 3,
    color: Color.headingColor,
  },
  rowBetween: {flex: 1, justifyContent: 'space-between'},
  PlusMinusBtnSt: {
    paddingHorizontal: '5%',
    paddingVertical: '1%',
    fontSize: 14,
    fontWeight: 'bold',
    textAlignVertical: 'center',
    textAlign: 'center',
    flex: 1,
    height: '100%',
    color: 'black',
  },
  PlusMinusMainStyle: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: Color.ThemeColor,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ProductViewCartMain: {
    borderWidth: 1,
    borderColor: Color.borderColors,
    marginHorizontal: '4%',
    marginTop: '3%',
    marginBottom: '1%',
    borderRadius: 5,
    padding: '3%',
    flexDirection: 'row',
    elevation: 2,
    backgroundColor: 'white',
  },
  ProductViewCartImage: {flex: 0.3, width: '100%', height: 80, borderRadius: 5},
  GeneralBorder: {
    borderWidth: 1,
    borderColor: Color.borderColors,
    borderRadius: 5,
    marginHorizontal: '4%',
    marginVertical: '2%',
    padding: '3%',
    elevation: 2,
    backgroundColor: 'white',
  },
  ListBetweenText: {fontFamily: fonts.medium, fontSize: 12, color: '#223263'},
  iconTwoTextmainView: {
    flexDirection: 'row',
    paddingHorizontal: '4%',
    paddingVertical: '6%',
    justifyContent: 'space-between',
  },
  iconTwoTexttitle: {
    marginLeft: 10,
    color: Color.headingColor,
    fontSize: 14,
    fontFamily: fonts.bold,
    textAlignVertical: 'center',
  },
  iconTwoTexttitlesecond: {
    fontFamily: 'Metropolis-Medium',
    fontWeight: '400',
    fontSize: 12,
    color: Color.neutralGray,
    marginTop: 3,
  },
  ProdetailsTitlte: {
    color: Color.headingColor,
    fontSize: 20,
    fontFamily: fonts.bold,
  },
  TitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: '4%',
  },
  AddCartProDetails: {width: '50%', alignSelf: 'center', marginTop: '20%'},
  IconTextMainStyle: {padding: 10, width: wp('20%'), marginHorizontal: 5},
  CartTwoTextMain: {
    borderRadius: 5,
    width: wp('29%'),
    marginRight: wp('3%'),
    marginLeft: wp('1%'),
    alignItems: 'center',
    paddingVertical: wp('1%'),
    elevation: 5,
    backgroundColor: 'white',
    marginVertical: '10%',
  },
  adminCardFeature: {
    elevation: 5,
    backgroundColor: 'white',
    marginBottom: 10,
    borderRadius: 5,
    marginLeft: wp('1%'),
    marginRight: wp('3%'),
    marginVertical: wp('3%'),
    paddingVertical: 8,
  },
  ChatItemContainer: {
    flexDirection: 'row',
    elevation: 3,
    borderWidth: 1,
    padding: wp('2%'),
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'lightgrey',
    marginVertical: 5,
    ...IOSShadow,
  },
  chatProfileView: {
    elevation: 3,
    borderWidth: 1,
    width: wp('10'),
    height: wp('10'),
    marginEnd: '2%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: wp('10'),
    ...IOSShadow,
  },
  chatTitleName: {
    color: Color.headingColor,
    fontSize: 16,
    fontFamily: fonts.bold,
  },
  chatContent: {
    color: 'gray',
    fontSize: 14,
    marginTop: '1%',
  },
  ChatMessageItemContainer: {
    flexDirection: 'row',
    elevation: 3,
    maxWidth: wp('60%'),
    borderWidth: 1,
    padding: wp('2%'),
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: 'lightgrey',
    margin: 5,
    ...IOSShadow,
  },
});

export default Theme;
